language: haskell

ghc:
  - 7.8

before_install:
  - cabal install happy
  - cabal install hlint

install:
  - cabal install --enable-tests --only-dependencies
  - cabal configure --enable-tests
  - cabal build

script:
  - hlint src testsuite
  - cabal test

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

deploy:
  provider: releases
  api-key:
    secure: "JkeIs3oHq3H3JraOPcuSPfYz0UmwW9PVF43DVnrvWVnT1bIql83YkyEnn8Ac93ybdsewQMUhkEDOBASRcyUI2IAv0/jcf3mmdGkU4lPtz4DlCrygv6e4jkHFaAcSH6T4Kjj+bykWiDTOgUVQu9N67HXAm9M3ll5f+wPerHgSZGw="
  file: dist/build/multiblog/multiblog
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

sudo: false
