language: haskell

ghc:
  - 7.8

before_install:
  - cabal install hlint
  - cabal sandbox init

install:
  - cabal configure --enable-tests
  - cabal install --only-dependencies
  - cabal build

script:
  - cabal test

cache:
  directories:
    - .cabal-sandbox

sudo: false
