sudo: false

language: generic

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  timeout: 900

addons:
  apt:
    packages:
      - wkhtmltopdf
      - xvfb

before_install:
- mkdir -p ~/.local/bin
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc test --bench --dry-run
- stack --no-terminal --install-ghc test --bench --only-dependencies
- stack --no-terminal --install-ghc install hlint

script:
- hlint src testsuite
- stack --no-terminal test --bench --no-run-benchmarks

before_deploy:
- cp $(stack path --local-install-root)/bin/multiblog .

deploy:
  provider: releases
  api-key:
    secure: "JkeIs3oHq3H3JraOPcuSPfYz0UmwW9PVF43DVnrvWVnT1bIql83YkyEnn8Ac93ybdsewQMUhkEDOBASRcyUI2IAv0/jcf3mmdGkU4lPtz4DlCrygv6e4jkHFaAcSH6T4Kjj+bykWiDTOgUVQu9N67HXAm9M3ll5f+wPerHgSZGw="
  file: multiblog
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
