#!/bin/sh

apt update
apt install --yes xvfb wget

TMP_DEB=$(mktemp --suffix .deb)
trap 'rm -f $TMP_DEB' EXIT INT TERM HUP
wget -O "$TMP_DEB" https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.jammy_amd64.deb
apt install --yes "$TMP_DEB"
