name: multiblog
version: '0.1'
synopsis: Blog engine for koterpillar.com
description: Static blog engine with multilingual support
category: Web
author: Alexey Kotlyarov
maintainer: a@koterpillar.com
license: MIT
dependencies:
- base >=4.7 && <5
- blaze-html
- blaze-markup
- bytestring
- containers
- data-default-class
- feed
- happstack-server
- iso639
- mtl
- pandoc
- text
- twitter-conduit
- xml-conduit
- xml-types
- yaml
library:
  source-dirs: src
  dependencies:
  - aeson
  - authenticate-oauth
  - boomerang
  - directory
  - filepath
  - http-conduit
  - lens
  - lifted-base
  - network
  - optparse-generic
  - pandoc-types
  - process
  - process-extras
  - shakespeare
  - split
  - tagsoup
  - time
  - transformers
  - twitter-types
  - unix
  - web-routes
  - web-routes-boomerang
  - web-routes-happstack
  - web-routes-th
executables:
  multiblog:
    main: Main.hs
    source-dirs: app
    dependencies:
    - multiblog
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
tests:
  tests:
    main: TestMain.hs
    source-dirs:
    - testsuite
    dependencies:
    - multiblog
    - HTF
    - HUnit
    - derive
    - quickcheck-instances
stability: Experimental
