name: multiblog
version: '0.1'
synopsis: Blog engine for koterpillar.com
description: Static blog engine with multilingual support
category: Web
author: Alexey Kotlyarov
maintainer: a@koterpillar.com
license: MIT
dependencies:
- base >=4.7 && <5
- aeson
- authenticate-oauth
- blaze-html
- blaze-markup
- boomerang
- bytestring
- containers
- data-default-class
- directory
- feed
- filepath
- happstack-server
- http-conduit
- iso639
- lens
- lifted-base
- mtl
- network
- optparse-generic
- pandoc
- pandoc-types
- process
- process-extras
- shakespeare
- split
- tagsoup
- text
- time
- transformers
- twitter-conduit
- twitter-types
- unix
- utf8-string
- web-routes
- web-routes-boomerang
- web-routes-happstack
- web-routes-th
- xml-conduit
- xml-types
- yaml
executables:
  multiblog:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -Wall
    - -Werror
tests:
  tests:
    main: TestMain.hs
    source-dirs:
    - src
    - testsuite
    dependencies:
    - HTF
    - HUnit
    - derive
    - quickcheck-instances
stability: Experimental
