resolver: lts-12.24
packages:
- '.'
ghc-options:
  '$everything': -threaded
extra-deps:
  - twitter-conduit-0.3.0
  - twitter-types-0.7.2.2
  - twitter-types-lens-0.7.2
flags:
  pandoc:
    embed_data_files: true
