resolver: lts-12.24
packages:
- '.'
ghc-options:
  '$everything': -threaded
extra-deps:
  - boomerang-1.4.5.5
  - derive-2.6.4
  - twitter-conduit-0.3.0
  - twitter-types-0.7.2.2
  - twitter-types-lens-0.7.2
  - web-routes-boomerang-0.28.4.2
  - web-routes-happstack-0.23.11
  - web-routes-th-0.22.6.3
flags:
  pandoc:
    embed_data_files: true
