name: Build

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --yes xvfb wget
          wget -O wkhtmltox.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
          sudo apt install --yes ./wkhtmltox.deb
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Stack
        run: stack upgrade || curl -sSL https://get.haskellstack.org/ | sh -s - -f
      - name: Set up cache
        uses: actions/cache@v1
        with:
          key: stack
          path: ~/.stack
      - name: Install dependencies
        run: |
          stack --no-terminal --install-ghc test --only-dependencies
      - name: Test
        run: |
          stack --no-terminal test

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Stack
        run: stack upgrade || curl -sSL https://get.haskellstack.org/ | sh -s - -f
      - name: Set up cache
        uses: actions/cache@v1
        with:
          key: stack
          path: ~/.stack
      - name: Install dependencies
        run: |
          stack --no-terminal --install-ghc test --only-dependencies
      - name: Build
        run: |
          stack --no-terminal build --copy-bins --local-bin-path .
          docker build 
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Calculate Docker tag
        id: tag
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '^refs/tags/v'
          string: ${{ github.ref }}
          replace-with: ''
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/koterpillar/multiblog:${{ steps.tag.outputs.replaced }}
