name: Renovate Lockfile Update

on:
  push:
    branches:
      - renovate/**

jobs:
  update-stack-lockfile:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and test
        uses: freckle/stack-action@v5
        with:
          stack-build-arguments: --dry-run
      - name: Update lockfile
        run: |
          if git diff --name-only | grep -q 'stack.yaml.lock'; then
            git config user.name "unused"
            git config user.email "unused@users.noreply.github.com"
            git add stack.yaml.lock
            git commit --amend --no-edit
            git push -f
          fi
